FROM gcr.io/tensorflow/tensorflow:latest-py3

LABEL com.tomasbasham.maintainer "Tomas Basham <me@tomasbasham.co.uk>" \
      com.tomasbasham.description "Tensorflow"

RUN pip install --no-cache-dir keras
